### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=node

### ISSUE THREAD

**Issue by jasonmarysael** [kriszyp/lmdb-js#192]
Version: 2.6.8

While trying to execute a serverless function on Vercel (which is calling the lmdb store) I'm getting the following error:

`Error: Runtime exited with error: exit status 1
Runtime.ExitError
2022-10-13T15:46:32.414Z	ERROR	Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.16.0
    loaded from: /var/task/node_modules/lmdb and package: @lmdb/lmdb-linux-x64
    at Function.load.path (/var/task/node_modules/node-gyp-build-optional-packages/index.js:64:9)
    at load (/var/task/node_modules/node-gyp-build-optional-packages/index.js:20:30)
    at file:///var/task/node_modules/lmdb/native.js:9:26
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
Error: Runtime exited with error: exit status 1
Runtime.ExitError`

During the build fase in Vercel (which also uses the lmdb store) everything seems to work fine. What could be the cause of this?

**Comment by jasonmarysael** [comment]
@kriszyp this is the content from the node_modules/@lmdb/lmdb-linux-x64 directory (listed during the build phase on the machine which is calling the function): 

![image](https://user-images.githubusercontent.com/28600053/195780082-8a1dd530-da37-4435-9ca6-83b9fab0a8df.png)

I also tried to manually copy the binaries like this:

![image](https://user-images.githubusercontent.com/28600053/195780360-a17f1d8f-4e86-415d-bbcd-41276887bb56.png)

Unfortunately the issue remains :/

**Comment by jasonmarysael** [comment]
@kriszyp 
You might be right regarding the changing content during the execution of the serverless function:

when listing the files of the node_modules/lmdb during build I get this:

![image](https://user-images.githubusercontent.com/28600053/195886138-3367678d-aa8f-487a-9d97-5ff487203158.png)

during the execution of the serverless function:

![image](https://user-images.githubusercontent.com/28600053/195886589-49701dce-0127-4fa4-8554-68aef1ec9ae9.png)

not sure why some files are missing/not being synced...

**Comment by kriszyp** [comment]
Is it only sync'ing .js files (the included dirs are the ones with .js files)? Or similarly, maybe there is some type of tree-shaking that copies transitively required .js files? I believe that when lmdb-js is used with bundlers, sometimes there are some creative methods that are necessary to ensure the binaries are also included.

**Comment by Josefer25** [comment]
Same bug here, what can we do?

**Comment by KonstantinBulgakov** [comment]
Hello
I have got a vary similar (or may be the same) behaviour in Vercel
Build runs fine but in runtime I see errors.
Is there any workaround to fix it:
```
⨯ Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.13.1
attempted loading from: /var/task/node_modules/.pnpm/lmdb@3.0.12/node_modules/lmdb and package: @lmdb/lmdb-linux-x64
Error resolving package: Cannot find module '@lmdb/lmdb-linux-x64'
Require stack:
- /var/task/node_modules/.pnpm/lmdb@3.0.12/node_modules/lmdb/package.json
at load.resolve.load.path (/var/task/node_modules/.pnpm/node-gyp-build-optional-packages@5.2.2/node_modules/node-gyp-build-optional-packages/node-gyp-build.js:85:9)
at load (/var/task/node_modules/.pnpm/node-gyp-build-optional-packages@5.2.2/node_modules/node-gyp-build-optional-packages/node-gyp-build.js:28:30)
at file:///var/task/node_modules/.pnpm/lmdb@3.0.12/node_modules/lmdb/native.js:51:26
```

**Comment by KonstantinBulgakov** [comment]
Hi [kriszyp](https://github.com/kriszyp)
Sorry for disturbing you but I really like lmdb-js and want to use it in a project. It works fine locally (on Mac) but I can't find a way how to use it in production. Can this issue be related with ubuntu version?

**Comment by kriszyp** [comment]
As noted in the error, it is looking for `@lmdb/lmdb-linux-x64` package which should have been installed during the install on linux. Can you tell if that package is present?

**Comment by KonstantinBulgakov** [comment]
I can't see node_modules in Vercel output. But I beleave that you are right the reason is correctly written in an error message. Also I found a post https://github.com/vercel/vercel/discussions/4338 and it is mentiond there that sometimes some dependensies can be omited from vercel output. 
So finally I wrote to Vercel support - probably they will help.
@kriszyp Thank you for response. I will report here in case I get additional info.

**Comment by kriszyp** [comment]
I don't know if this is the case, but you will run into problems if you install lmdb on one OS/arch, and then move that bundle of files to another OS/arch, since it will have the wrong binary for the target OS. lmdb-js does have an NPM script `download-lmdb-prebuilds` to download all the prebuilt binaries if you are creating a bundle that will be distributed to multiple OSes.
