### ISSUE TITLE
clearAsync fails when key-encoding = 'binary' and encryption

### ISSUE THREAD

**Issue by leiffoged** [kriszyp/lmdb-js#199]
clearAsync doesnt 

Repro:
1/ Create a new DB. Settings: 
{keyEncoding: 'binary'}

2/ Call clearAsync
TypeError: Cannot convert undefined or null to object
    at Buffer.set (<anonymous>)
    at LMDBStore.writeBufferKey [as writeKey] (/Users/leif/code/node-modules/lmdb/dist/index.cjs:1258:9)
    at writeInstructions (/Users/leif/code/node-modules/lmdb/dist/index.cjs:284:25)
    at LMDBStore.clearAsync (/Users/leif/code/node-modules/lmdb/dist/index.cjs:838:11)

Does not fail with keyEncoding = 'ordered-binary'

**Comment by kriszyp** [comment]
Fix should be available in v2.6.9.

**Comment by leiffoged** [comment]
Woo!! Thank you!
