### ISSUE TITLE
 Adding Support for Win32 ARM64

### ISSUE THREAD

**Issue by alan-agius4** [kriszyp/lmdb-js#295]
Currently, this library does not support the Win32 ARM64 platform, resulting in the following error during runtime:

```
No native build was found for platform=win32 arch=arm64 runtime=node abi=127 uv=1 armv=8 libc=glibc node=22.3.0
    attempted loading from: D:\Junk\my-app\node_modules\lmdb and package: @lmdb/lmdb-win32-arm64
```

**Comment by kriszyp** [comment]
Are you aware of _any_ Node.js native packages that have managed to do Windows ARM builds yet? I haven't found any, and I believe that this actually requires a Windows ARM runner to do the compilation, which is not currently not available anywhere:
https://github.com/parcel-bundler/lightningcss/issues/724
https://github.com/lovell/sharp/issues/2553
https://github.com/TryGhost/node-sqlite3/issues/874

**Comment by alan-agius4** [comment]
Esbuild and rollup seem to support ARM64

- https://unpkg.com/browse/rollup@4.18.0/package.json (@rollup/rollup-win32-arm64-msvc)
 - https://unpkg.com/browse/esbuild@0.21.5/package.json (@esbuild/win32-arm64)

**Comment by richardmynameis** [comment]
Hi @alan-agius4 did you find a way how to solve this error ? 
I think many more people who develop on mac in parallels will have same issue

**Comment by kriszyp** [comment]
It looks like rollup is using rust/cargo to do the builds, and I don't even see where esbuild builds are performed. I am not sure how these would inform how to run node-gyp build with an ARM target. I definitely would still love to do add support for Windows ARM if anyone finds anything that could help. PRs obviously welcome too.

**Comment by hakimio** [comment]
esbuild is using go to build `win32-arm64`:
[Makefile](https://github.com/evanw/esbuild/blob/360d47230813e67d0312ad754cad2b6ee09b151b/Makefile#L326)
[go source code](https://github.com/evanw/esbuild/tree/360d47230813e67d0312ad754cad2b6ee09b151b/cmd/esbuild)

**Comment by kriszyp** [comment]
I don't really follow how the Makefile runs those source code files (not really a Go programmer, and seems like rewriting the lmdb-js build process would be a pretty big change and difficult to maintain, but again, PRs are welcome.)

**Comment by jbennie** [comment]
Hi this is a show stopper for developing angular aps on windows on ARM without resorting to wsl. (Snapdragon x1E84100 )

The problem however might be as simle as a path with a whitespace not being parsered.  
See my error log below - specifically the section when trying to fallback to a native compile - I've check all the correct dependencies exist on my host. VS2022 with MVCS C++ ARM MVC/ALT Libs etc. 
 
npm error path K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\lmdb
npm error command failed
npm error command C:\windows\system32\cmd.exe /d /s /c node-gyp-build-optional-packages
npm error K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:85
npm error   throw new Error(errMessage)
npm error   ^
npm error
npm error Error: No native build was found for platform=win32 arch=arm64 runtime=node abi=127 uv=1 armv=8 libc=glibc node=22.5.1
npm error     attempted loading from: K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\lmdb and package: @lmdb/lmdb-win32-arm64
npm error Error resolving package: Cannot find module '@lmdb/lmdb-win32-arm64'
npm error Require stack:
npm error - K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\lmdb\package.json
npm error
npm error     at load.resolve.load.path (K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:85:9)
npm error     at load (K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:28:30)
npm error     at Object.<anonymous> (K:\github\cssproject\frontendtools\AP2020\ap-app\node_modules\node-gyp-build-optional-packages\build-test.js:19:19)
npm error     at Module._compile (node:internal/modules/cjs/loader:1504:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1282:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1098:12)
npm error     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
npm error     at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
npm error
npm error Node.js v22.5.1
npm error
npm error The failure above indicates the primary issue with the native builds which are included for all major platforms. Will now attempt to build the package locally in case this can be resolved by re-compiling.
**npm error 'C:\Program' is not recognized as an internal or external command,**
npm error operable program or batch file.

**Comment by miladfm** [comment]
any update?

**Comment by kriszyp** [comment]
> any update?

Yes, we have been continuing to work hard on this. I believe the Windows ARM64 runners are only available with paid accounts (or has that changed), so working @harperdb, to try get builds running. We have the process started, but the current problem seems to be that Visual Studio is missing on Windows ARM64 runners, which is critical for the builds:
https://github.com/HarperDB/lmdb-js/actions/runs/11292316151/job/32695626446
Certainly open to ideas on how to resolve this. We would still really love to get Win ARM64 builds available as soon as possible, but this is the current roadblock.

**Comment by miladfm** [comment]
Thank you for the quick reply.

I also found a temporary fix to run the app. In my case, I’m using Angular, and by updating my pnpm config as shown below, I no longer receive errors. However, this approach isn’t native and increases build time. It’s a workaround until the current issue is resolved.

Here’s what I used:
```
"pnpm": {
  "overrides": {
    "@angular/build>lmdb": "-"
  }
},
"optionalDependencies": {
  "lmdb": "3.1.4"
}
```
Source: https://github.com/angular/angular-cli/issues/27882#issuecomment-2395029997

**Comment by brunomantovani** [comment]
For this problem, I decided to use the x64 version of Node instead of ARM64 since this library does not support those platforms.

**Comment by cap10morgan** [comment]
I think we'll have a much easier time getting this done once the GitHub Actions folks finish this work: https://github.com/actions/partner-runner-images/issues/19

**Comment by horros** [comment]
Running in x64 emulation mode is certainly possible and it is usable, but it is slow. Arm64 hosted github action runners are available for free for public repos now so is there maybe a possibility this would nudge forward?

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

**Comment by snmishra** [comment]
> Are you aware of _any_ Node.js native packages that have managed to do Windows ARM builds yet? I haven't found any, and I believe that this actually requires a Windows ARM runner to do the compilation, which is not currently not available anywhere, AFAIK: [parcel-bundler/lightningcss#724](https://github.com/parcel-bundler/lightningcss/issues/724) [lovell/sharp#2553](https://github.com/lovell/sharp/issues/2553) [TryGhost/node-sqlite3#874](https://github.com/TryGhost/node-sqlite3/issues/874)

Windows ARM runners are now available on GitHub. In my local testing, lmdb-js builds fine using node-gyp. Any chance it could be enabled in CI? The following patch may work (I haven't checked in CI)

```
diff --git a/.github/workflows/prebuild.yml b/.github/workflows/prebuild.yml
index 31661e99c..9a1c12b5c 100644
--- a/.github/workflows/prebuild.yml
+++ b/.github/workflows/prebuild.yml
@@ -57,6 +57,31 @@ jobs:
         if: startsWith(github.ref, 'refs/tags/')
         with:
           files: prebuild-win32.tar
+  build-test-win32-arm64:
+    #if: startsWith(github.ref, 'refs/tags/')
+    env:
+      LMDB_DATA_V1: ${{ contains(github.ref, '-v1') }}
+    runs-on: windows-11-arm
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 16
+      - run: npm install
+      - run: npm run build
+      - run: npm test
+        if: ${{ !contains(github.ref, '-v1') }}
+      - run: npm run prebuild-win32
+        env:
+          PREBUILD_ARCH: arm64
+      - run: tar --create --verbose --file=prebuild-win32-arm64.tar -C prebuilds .
+        if: startsWith(github.ref, 'refs/tags/')
+      - name: Prebuild
+        uses: softprops/action-gh-release@v2
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          files: prebuild-win32-arm64.tar
   build-centos-7:
     #if: startsWith(github.ref, 'refs/tags/')
     env:
```

**Comment by kriszyp** [comment]
Hmm, it does seem to make it further than I have seen it go before. But it is failing on the final prebuild step... Does this work for you locally?
`npx prebuildify-platform-packages --debug --napi --platform-packages --target 20.18.0`

**Comment by snmishra** [comment]
Ah, forgot that I made an edit to `prebuildify-platform-packages` package. `proc.spawn` needs `shell: true` option on Windows because the `node-gyp` command is a `.cmd` file and those are not run by default because of some security fix. I'm surprised the Windows x86_64 works, since this limitation should apply there too.
