### ISSUE TITLE
MDB error cursor full

### ISSUE THREAD

**Issue by xrchz** [kriszyp/lmdb-js#299]
```
node_modules/lmdb/read.js:58
					throw lmdbError(rc);
					      ^

Error: MDB_CURSOR_FULL: Internal error - cursor stack limit reached
    at LMDBStore.getBinaryFast (file:///home/ramana/rockettheft/node_modules/lmdb/read.js:58:12)
    at LMDBStore.get (file:///home/ramana/rockettheft/node_modules/lmdb/read.js:228:22)
    at populateCache (file:///home/ramana/rockettheft/run.js:463:19)
    at file:///home/ramana/rockettheft/run.js:553:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: -30787
}

Node.js v22.4.0
```

**Comment by xrchz** [comment]
I will try again with `lmdb@2.9.4`...

**Comment by kriszyp** [comment]
Do you have more information on how to reproduce this?
