### ISSUE TITLE
filter breaks following forEach in 3.1.0-3.1.5

### ISSUE THREAD

**Issue by awick** [kriszyp/lmdb-js#313]
The following code works in 3.0.14 but not 3.1.0-3.1.5

```const { open } = require('lmdb');
const store = open({ path: '/tmp/cont3xt-db', compression: true });
const overviewStore = store.openDB('overviews');

overviewStore.getRange({})
  .forEach(({ key, value }) => { console.log("ALW1", key, value); });

overviewStore.getRange({})
  .filter(({ key, value }) => { return true; })
  .forEach(({ key, value }) => { console.log("ALW2", key, value); });
```

Looks like some kind options are expected to be set

```/Users/andywick/test/node_modules/lmdb/dist/index.cjs:1440
			if (options.continueOnRecoverableError)
			            ^

TypeError: Cannot read properties of undefined (reading 'continueOnRecoverableError')
    at iterable.iterate (/Users/andywick/test/node_modules/lmdb/dist/index.cjs:1440:16)
    at RangeIterable.forEach (/Users/andywick/test/node_modules/lmdb/dist/index.cjs:1448:40)
    at Object.<anonymous> (/Users/andywick/test/foo.js:10:4)
```

**Comment by awick** [comment]
Confirmed 3.1.6 works for us, thanks!
